<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.1.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.72.0" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.72.0.3944" />
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.70.0.3819" />
    <PackageReference Include="GoogleAuthenticator" Version="3.1.0" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Pay2Me.Data\Pay2Me.Data.csproj" />
		<ProjectReference Include="..\Pay2Me.Jwt\Pay2Me.Jwt.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\" />
	</ItemGroup>

</Project>
